config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='polls-home'),
    path('<int:pk>/', views.DetailView.as_view(), name='polls-detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='polls-results'),
    path('<int:question_id>/vote', views.vote, name='polls-vote'),
    path('<int:question_id>/pie-chart/', views.pie_chart, name='polls-pie-chart'),
    path('signup/', views.signup, name='signup'),
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

class Question(models.Model):
    """
    Stores a set of Question and Question's choice.

    Property
    --------
    text: str
        Question text, max max_length 200

    pub_date: datetime
        Time that the question has been created.
    """

    text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(null=True, blank=True)

    def can_vote(self):
        """Check that poll is ended."""
        now = timezone.now()
        if self.end_date is None:
            return True
        return self.end_date >= now

    def was_published_recently(self):
        """Make sure that the question object is not come from the future."""
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def get_pub_date(self):
        """Return the passing time."""
        return self.pub_date.strftime("%d %b %y [%H:%M]")

    def get_end_date(self):
        """Return remaining time."""
        return self.end_date.strftime("%d %b %y [%H:%M]")

    def __str__(self):
        return self.text


class Choice(models.Model):
    """
    Store Choice object that related to :model: `polls.Question`.

    Property
    --------
    question: Question
        Question object where the Choice is.
    text: str
        Choice text, max length 200.

    vote: int
        Number of vote for that choice.
    """

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    @property
    def votes(self):
        return self.question.vote_set.filter(choice=self).count()
    
    def __str__(self):
        return self.text

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.contrib import messages
from django.views.generic import ListView, DetailView
from django.utils import timezone
from django.db.models import Q
from .models import Question, Choice
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
import logging
from django.contrib.auth.signals import user_logged_in, user_logged_out, user_login_failed
from django.dispatch import receiver

logging.basicConfig(filename='userlogging.log',level=logging.DEBUG)
logger = logging.getLogger("polls") 

def pie_chart(request, question_id): # pragma: no cover
    """Show pie chart on data visualize page."""
    question = get_object_or_404(Question, pk=question_id)
    labels = []
    data = []
    result = reverse('polls:polls-results', args=(question.id,))
    queryset = question.choice_set.all()
    for choice in queryset:
        labels.append(choice.text)
        data.append(choice.votes)

    return render(request, 'polls/pie_chart.html', {
        'labels': labels,
        'data': data,
        'result': result,
        'question': question,
    })


class IndexView(ListView):
    """Get the newest 5 polls question and display in ?/polls."""

    template_name = 'polls/home.html'
    context_object_name = 'latest_question_list'

    def get_context_data(self, *args, **kwargs):
        """Get a context data."""
        data = super(IndexView, self).get_context_data(*args, **kwargs)
        data['title'] = "List"
        return data

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        query_question = Question.objects.filter(Q(pub_date__lte=timezone.now()) | Q(end_date__isnull=True, pub_date__lte=timezone.now())).order_by('-pub_date')
        return query_question[:5]


class DetailView(DetailView):
    """Display the all choice of the selected question in ?/polls/<question.id>."""

    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Return every question that are published (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(DetailView):
    """Display all vote result of the selected question"""

    model = Question
    template_name = 'polls/results.html'

    def get_context_data(self, *args, **kwargs):
        """Get context data."""
        data = super(ResultsView, self).get_context_data(*args, **kwargs)
        data['title'] = "List"
        data['back_home'] = True
        return data

@login_required(login_url='/login/') 
def vote(request, question_id):
    """Save the voting result to question object that user selected"""
    # load question object
    question = get_object_or_404(Question, pk=question_id)
    user = request.user
    try:
        # check selected choice
        selected_choice = question.choice_set.get(pk=int(request.POST['choice']))
    except (KeyError, Choice.DoesNotExist):
        # User not select any choice
        # display warning messages
        messages.warning(request, "You didn't select a choice.", fail_silently=True)
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
        })
    else:
        # save vote
        if not question.can_vote():
            messages.error(request, "You voted failed! Polls ended", fail_silently=True)
            return HttpResponseRedirect(reverse('polls:polls-results', args=(question.id,)))
        if question.vote_set.filter(user=user).exists():
            vote = question.vote_set.get(user=user)
            vote.choice = selected_choice
            vote.save()
            messages.success(request, "You have successfully changed your vote.",fail_silently=True )  
        else:
            selected_choice.vote_set.create(user=request.user, question=question)
            selected_choice.save()
            messages.success(request, "You voted successfully.",fail_silently=True )
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:polls-results', args=(question.id,)))

def signup(request):
    """Register a new user."""
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_passwd = form.cleaned_data.get('password2')
            user = authenticate(username=username,password=raw_passwd)
            login(request, user)
            return redirect('polls:polls-home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form':form})


def get_client_ip(request):
    """Get the visitor’s IP address using request headers."""
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

# @receiver(user_logged_in)
# def user_logged_in_callback(sender, request, user, **kwargs):  
#     ip = get_client_ip(request)
#     logger.info(f"{user} logged in from {ip}")

# @receiver(user_logged_out)
# def user_logged_out_callback(sender, request, user, **kwargs):  
#     print('hello')
#     ip = get_client_ip(request)
#     logger.info(f"{user} logged out from {ip}")

# @receiver(user_login_failed)
# def user_login_failed_callback(sender, request,credentials, **kwargs):  
#     ip = get_client_ip(request)
#     logger.warning(f'login failed for: {credentials} from {ip}')
    
    

polls/templates/polls/all_result.html
{% extends "polls/base.html" %}
{% block content %}
{% if latest_question_list %}
    {% for question in latest_question_list %}
    <!-- list all ended polls -->
        <div class="polls-section">
            <a class="question_text_polls" href="{% url 'polls:polls-results' question.id %}">
                {{ question.text }}
            </a>
        </div>
    {% endfor %}
{% else %}
    <h3 align="center">No polls are available.</h3>
{% endif %}
{% endblock content %}

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<head>
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Comfortaa:wght@700&display=swap');
    </style>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- polls static polls/main.css -->
    <link rel="stylesheet" type="text/css" href="{% static 'polls/main.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <title>KU POLLS</title>
</head>
<body>
    <!-- Navigation bar -->
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <!-- KU POLLS logo link to /polls page -->
                <a class="nav-link icon" href="{% url 'polls:polls-home' %}">KU POLLS</a>
                {% if user.is_authenticated %}
                <a class="nav-link icon" href="{% url 'logout' %}">logout</a>
                {% else %}
                <a class="nav-link icon" href="{% url 'login' %}">login</a>
                {% endif %}
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <!-- message section -->
        <div>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {{ message.tags }} mb-0 alert-dismissible fade show" role="alert">
                      <strong>Message: </strong>  {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <!-- content section -->
            {% block content %}{% endblock %}
        </div>

    </main>
    
</body>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% block content %}
<!-- content header -->
<h1>{{ question.text }}</h1>
<hr style="height:2px;border-width:0;color:gray;background-color:gray;margin-bottom: 30px;">
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<!-- main content -->
<!-- request api question vote -->
{% if not question.can_vote %}


<h3>Poll is ended</h3>
<div style="margin-top: 50px">
    <a class="next-page float-left" href="{% url 'polls:polls-home' %}">Back</a>
    <a class="next-page" href="{% url 'polls:polls-results' question.id %}">Result</a>
</div>


{% else %}


<form action="{% url 'polls:polls-vote' question.id %}" method="post">
{% csrf_token %}
{% if question.choice_set.all %}
    {% for choice in question.choice_set.all %}
        <!-- display list of choice in question.id -->
        <input class="choice_input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label class="choice_label" for="choice{{ forloop.counter }}">{{ choice.text }}</label><br>
    {% endfor %}
    <hr style="height:2px;border-width:0;color:gray;background-color:gray;margin-bottom: 30px;">
        <!-- submit vote and go to the next page (?/result) -->
        <a class="next-page float-left" href="{% url 'polls:polls-home' %}">Back</a>
        <input type="submit" class="next-page float-right" value="Vote">
    </form>

    
{% else %}


<div class="container">
    <h3 style="color: #870000">No choice in this question</h3>
    <a class="next-page" href="{% url 'polls:polls-home' %}">Back</a>
</div>


{% endif %}


{% endif %}

{% endblock content %}

polls/templates/polls/home.html
{% extends "polls/base.html" %}
{% block content %}
{% if latest_question_list %}
    {% for question in latest_question_list %}
    <!-- list 5 newest polls -->
        <div class="polls-section">
            {% if question.can_vote %}
            <a class="question_text_polls" href="{% url 'polls:polls-detail' question.id %}">
                {{ question.text }}
            </a>
            {% else %}
            <a class="question_text_polls" href="{% url 'polls:polls-results' question.id %}">
                {{ question.text }}
            </a>
            {% endif %}
            <a class="next-page float-right" style="padding: 25px 20px; border: 3px" href="{% url 'polls:polls-results' question.id %}">Result</a>
            {% if question.can_vote%}
            <a class="next-page float-right" style="padding: 25px 20px; border: 3px" href="{% url 'polls:polls-detail' question.id %}">Vote</a>
            {% endif %}
            <div class="poll-pub-date">
                <!-- date format ex. 22:29 31-aug-21 -->
                <small>Open {{ question.get_pub_date }}</small>
                <br>
                {% if not question.can_vote %}
                    <small>ended</small>
                {% else %}
                    {% if question.end_date %}
                    <small>Close {{ question.get_end_date }}</small>
                    {% else %}
                    <small>Close None</small>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% else %}
    <h3 align="center">No polls are available.</h3>
{% endif %}
{% endblock content %}

polls/templates/polls/pie_chart.html
{% extends "polls/base.html" %}

{% block content %}
  <h1>{{ question.text }}</h1>
  <hr style="height:2px;border-width:0;color:gray;background-color:gray;margin-bottom: 30px;">
  <div id="container"  style="width: 75%;margin-left: 10%; position:relative;">
    <canvas id="pie-chart"></canvas>
    
  </div>
  <a class="next-page" href="{% url 'polls:polls-results' question.id %}">Back</a>
  

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>
    var config = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ data|safe }},
          backgroundColor: [
            '#E59866 ', '#F9E79F', '#82E0AA', '#85C1E9', '#AF7AC5'
          ],
          label: 'votes'
        }],
        labels: {{ labels|safe }}
      },
      options: {
        responsive: true
      }
    };


    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

  </script>

{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}
{% block content %}
<!--  content header  -->
<h1>{{ question.text }}</h1>
<hr style="height:2px;border-width:0;color:gray;background-color:gray;margin-bottom: 30px;">

<!--  main content  -->
<ul>
{% for choice in question.choice_set.all %}
    <!--  display a list of the number of vote for each choice  -->
    <li class="choice_voted">{{ choice.text }}&nbsp;&nbsp;|&nbsp;&nbsp;{{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<!-- link redirect to polls/question.id -->
<a class="next-page float-left" href='{% url 'polls:polls-home' %}'>Back</a>
<a class="next-page float-right" href="{% url 'polls:polls-pie-chart' question.id %}">Data Visualize</a>
{% if question.can_vote %}
<a class="next-page float-right" href="{% url 'polls:polls-detail' question.id %}">Vote again?</a>
{% endif %}

{% endblock content %}